"""Credenciales acotadas que no representan a una persona.

Hasta aqui la unica credencial era el JWT del inicio de sesion, y eso obligaba
a dos apanos: el trabajador se conectaba directo a la base, de modo que
entregarselo a alguien era entregarle la base entera, y el participante del
estudio entraba en el navegador que el investigador dejaba con su sesion
abierta.

Del secreto solo se guarda la huella SHA-256. El token en claro se entrega una
vez al emitirlo. `subject_id` no lleva clave foranea a proposito: apunta a un
proyecto o a un participante segun el tipo, y ponersela obligaria al contexto
de acceso a conocer los dos esquemas ajenos.

Revision ID: e262fe51f9d8
Revises: b4f92c1d7a08
Create Date: 2026-09-23 20:08:22.320006
"""
from alembic import op
import sqlalchemy as sa


revision = 'e262fe51f9d8'
down_revision = 'b4f92c1d7a08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_grants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject_kind', sa.String(length=20), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('secret_hash', sa.String(length=64), nullable=False),
    sa.Column('issued_by', sa.String(length=36), nullable=True),
    sa.Column('label', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("subject_kind IN ('worker','participation')", name='ck_access_grants_kind'),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_access_grants_subject', 'access_grants', ['subject_kind', 'subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_access_grants_subject', table_name='access_grants')
    op.drop_table('access_grants')
    # ### end Alembic commands ###
