"""La ficha del anexo B entra en la base.

Vivia en un formulario en linea aparte, y eso dejaba dos cosas al aire.

La pregunta del rol formal de seguridad activa el criterio de exclusion del
apartado 4.4, de modo que la exclusion dependia de que alguien leyera la hoja
de respuestas ANTES de dejar empezar a nadie. El dominio ya la rechazaba, pero
el campo no llegaba nunca y la regla no podia dispararse.

Y la experiencia es factor de control del analisis: cruzarla despues por un
codigo que el participante tecleo a mano es donde se pierden filas.

EL ENTERO DE ANIOS SALE Y ENTRA LA BANDA. El modelo guardaba anios y derivaba
tres bandas propias, mientras que la ficha preguntaba en cuatro tramos
distintos. Quien respondiera «De 1 a 3» podia caer en dos bandas del analisis y
no habia forma de saber en cual, porque el numero exacto nunca se pregunto.

La columna se anade con valor por defecto y luego se deja obligatoria, para que
la migracion no falle sobre filas existentes. En la practica no hay ninguna.

Revision ID: cf89d5c0e069
Revises: a131347907c9
Create Date: 2026-09-23 20:59:11.036316
"""
from alembic import op
import sqlalchemy as sa


revision = 'cf89d5c0e069'
down_revision = 'a131347907c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('experience_band', sa.String(length=12), nullable=False, server_default='de_1_a_3'))
    op.add_column('participants', sa.Column('main_language', sa.String(length=40), nullable=True))
    op.add_column('participants', sa.Column('alert_frequency', sa.String(length=12), nullable=True))
    op.add_column('participants', sa.Column('security_training', sa.String(length=12), nullable=True))
    op.drop_column('participants', 'years_of_experience')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('years_of_experience', sa.INTEGER(), nullable=False))
    op.drop_column('participants', 'security_training')
    op.drop_column('participants', 'alert_frequency')
    op.drop_column('participants', 'main_language')
    op.drop_column('participants', 'experience_band')
    # ### end Alembic commands ###
