"""esquema inicial

Revision ID: 926bbc628e96
Revises: 
Create Date: 2026-09-10 14:30:26.956155
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

revision = '926bbc628e96'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participantes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('codigo_anonimo', sa.String(length=20), nullable=False),
    sa.Column('anios_experiencia', sa.Integer(), nullable=False),
    sa.Column('tiene_rol_seguridad', sa.Boolean(), nullable=False),
    sa.Column('consentimiento_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('tiene_rol_seguridad = 0', name='ck_participantes_rol'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_anonimo')
    )
    op.create_table('proyectos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('lenguaje', sa.String(length=50), nullable=False),
    sa.Column('ruta_repositorio', sa.Text(), nullable=False),
    sa.Column('es_conjunto_publico', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ruta_repositorio')
    )
    op.create_table('transformaciones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hallazgo_original_id', sa.String(length=36), nullable=False),
    sa.Column('hallazgo_transformado_id', sa.String(length=36), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('anclaje_activo', sa.Boolean(), nullable=False),
    sa.Column('veredicto_original', sa.String(length=20), nullable=True),
    sa.Column('veredicto_transformado', sa.String(length=20), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('creada_en', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('hallazgo_original_id <> hallazgo_transformado_id', name='ck_transf_distintos'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hallazgo_original_id', 'hallazgo_transformado_id', 'anclaje_activo', name='uq_transf_par')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('correo', sa.String(length=160), nullable=False),
    sa.Column('contrasena_hash', sa.String(length=120), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("rol IN ('desarrollador','investigador','lider_tecnico')", name='ck_usuarios_rol'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('ejecuciones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('proyecto_id', sa.String(length=36), nullable=False),
    sa.Column('herramienta', sa.String(length=100), nullable=False),
    sa.Column('version_reglas', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('alcance', sa.Text(), nullable=True),
    sa.Column('total_hallazgos', sa.Integer(), nullable=False),
    sa.Column('validados', sa.Integer(), nullable=False),
    sa.Column('sarif_original', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('tomada_por', sa.String(length=120), nullable=True),
    sa.Column('motivo_fallo', sa.Text(), nullable=True),
    sa.Column('contexto_purgado', sa.Boolean(), nullable=False),
    sa.Column('iniciada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalizada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creada_en', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("estado IN ('pendiente','en_proceso','completada','fallida')", name='ck_ejecuciones_estado'),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ejecuciones_cola', 'ejecuciones', ['estado', 'creada_en'], unique=False)
    op.create_table('sesiones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('participante_id', sa.String(length=36), nullable=False),
    sa.Column('orden_condiciones', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('lote_primero', sa.String(length=10), nullable=False),
    sa.Column('lote_segundo', sa.String(length=10), nullable=False),
    sa.Column('completa', sa.Boolean(), nullable=False),
    sa.Column('iniciada_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finalizada_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['participante_id'], ['participantes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decisiones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sesion_id', sa.String(length=36), nullable=True),
    sa.Column('hallazgo_id', sa.String(length=36), nullable=False),
    sa.Column('participante_id', sa.String(length=36), nullable=False),
    sa.Column('valor', sa.String(length=20), nullable=False),
    sa.Column('segundos', sa.Float(), nullable=False),
    sa.Column('condicion', sa.String(length=20), nullable=False),
    sa.Column('es_vigente', sa.Boolean(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('creada_en', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("valor IN ('confirmado','descartado','dudoso')", name='ck_decisiones_valor'),
    sa.CheckConstraint('segundos > 0', name='ck_decisiones_segundos'),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesiones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_decisiones_hallazgo', 'decisiones', ['hallazgo_id'], unique=False)
    op.create_index('ix_decisiones_participante', 'decisiones', ['participante_id', 'condicion'], unique=False)
    op.create_table('hallazgos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ejecucion_id', sa.String(length=36), nullable=False),
    sa.Column('regla_id', sa.String(length=200), nullable=False),
    sa.Column('cwe', sa.String(length=20), nullable=True),
    sa.Column('severidad_regla', sa.String(length=20), nullable=False),
    sa.Column('archivo', sa.Text(), nullable=False),
    sa.Column('linea_inicio', sa.Integer(), nullable=False),
    sa.Column('linea_fin', sa.Integer(), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=True),
    sa.Column('huella', sa.String(length=64), nullable=False),
    sa.Column('verdad_conocida', sa.Boolean(), nullable=True),
    sa.Column('prioridad', sa.Float(), nullable=True),
    sa.Column('motivo_prioridad', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('linea_fin >= linea_inicio', name='ck_hallazgos_lineas'),
    sa.ForeignKeyConstraint(['ejecucion_id'], ['ejecuciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hallazgos_ejecucion', 'hallazgos', ['ejecucion_id'], unique=False)
    op.create_index('ix_hallazgos_huella', 'hallazgos', ['huella'], unique=False)
    op.create_index('ix_hallazgos_prioridad', 'hallazgos', ['ejecucion_id', 'prioridad'], unique=False)
    op.create_table('contextos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hallazgo_id', sa.String(length=36), nullable=False),
    sa.Column('funcion_contenedora', sa.Text(), nullable=False),
    sa.Column('llamadores', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('saneadores', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('lineas_disponibles', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('fuente_identificada', sa.Text(), nullable=True),
    sa.Column('profundidad_llamadores', sa.Integer(), nullable=False),
    sa.Column('degradado_a_archivo', sa.Boolean(), nullable=False),
    sa.Column('texto_contexto', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hallazgo_id'], ['hallazgos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hallazgo_id')
    )
    op.create_table('veredictos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hallazgo_id', sa.String(length=36), nullable=False),
    sa.Column('modelo', sa.String(length=120), nullable=False),
    sa.Column('version_modelo', sa.String(length=120), nullable=False),
    sa.Column('version_consulta', sa.String(length=120), nullable=True),
    sa.Column('temperatura', sa.Float(), nullable=False),
    sa.Column('repeticion', sa.Integer(), nullable=False),
    sa.Column('valor', sa.String(length=20), nullable=False),
    sa.Column('confianza', sa.Float(), nullable=True),
    sa.Column('lineas_citadas', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('anclaje_verificado', sa.Boolean(), nullable=False),
    sa.Column('intentos', sa.Integer(), nullable=False),
    sa.Column('justificacion', sa.Text(), nullable=True),
    sa.Column('respuesta_completa', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('latencia_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_entrada', sa.Integer(), nullable=True),
    sa.Column('tokens_salida', sa.Integer(), nullable=True),
    sa.Column('reutilizado_de', sa.String(length=36), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confianza IS NULL OR (confianza >= 0 AND confianza <= 1)', name='ck_veredictos_confianza'),
    sa.CheckConstraint('intentos BETWEEN 1 AND 2', name='ck_veredictos_intentos'),
    sa.ForeignKeyConstraint(['hallazgo_id'], ['hallazgos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hallazgo_id', 'modelo', 'version_modelo', 'repeticion', name='uq_veredictos_condicion')
    )
    op.create_index('ix_veredictos_hallazgo', 'veredictos', ['hallazgo_id'], unique=False)
    op.create_index('ix_veredictos_modelo', 'veredictos', ['modelo', 'version_modelo', 'repeticion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_veredictos_modelo', table_name='veredictos')
    op.drop_index('ix_veredictos_hallazgo', table_name='veredictos')
    op.drop_table('veredictos')
    op.drop_table('contextos')
    op.drop_index('ix_hallazgos_prioridad', table_name='hallazgos')
    op.drop_index('ix_hallazgos_huella', table_name='hallazgos')
    op.drop_index('ix_hallazgos_ejecucion', table_name='hallazgos')
    op.drop_table('hallazgos')
    op.drop_index('ix_decisiones_participante', table_name='decisiones')
    op.drop_index('ix_decisiones_hallazgo', table_name='decisiones')
    op.drop_table('decisiones')
    op.drop_table('sesiones')
    op.drop_index('ix_ejecuciones_cola', table_name='ejecuciones')
    op.drop_table('ejecuciones')
    op.drop_table('usuarios')
    op.drop_table('transformaciones')
    op.drop_table('proyectos')
    op.drop_table('participantes')
    # ### end Alembic commands ###
