"""El permiso viene de la relacion con el proyecto, no de un rango global.

Habia tres roles de cuenta, y de dieciseis comprobaciones del sistema trece
admitian indistintamente a `investigador` y `lider_tecnico`: la distincion no
existia de verdad. El tercero, `desarrollador`, no podia siquiera crear un
proyecto, de modo que quien se registraba no podia usar la herramienta.

El documento de arquitectura ya describia membresia sin llamarla asi: del lider
tecnico dice que «registra el proyecto, lanza el analisis y consulta en que
quedo el trabajo de su equipo», y del desarrollador que «recibe la lista
ordenada y decide sobre cada uno». Eso es lo que uno hace en su proyecto y lo
que hace quien fue invitado a el.

Quien crea el proyecto queda como su administrador, sin invitacion. El resto
entra invitado. Los dos deciden sobre hallazgos; lo que solo puede el
administrador es lo que afecta al proyecto entero.

`projects.owner_id` se conserva porque quien lo creo es un hecho, no un
permiso. El permiso vive en esta tabla.

Revision ID: 0d7281b14e8e
Revises: cf89d5c0e069
Create Date: 2026-09-23 21:22:32.946482
"""
from alembic import op
import sqlalchemy as sa


revision = '0d7281b14e8e'
down_revision = 'cf89d5c0e069'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('invited_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('administrador','miembro')", name='ck_member_role'),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_member_project_user')
    )
    op.create_index('ix_members_user', 'project_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_members_user', table_name='project_members')
    op.drop_table('project_members')
    # ### end Alembic commands ###
