"""esquema inicial

Revision ID: 89c7ef767641
Revises: 
Create Date: 2026-09-10 20:52:23.856231
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # lo emite el autogenerado sin prefijo
from sqlalchemy.dialects import postgresql

revision = '89c7ef767641'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('anonymous_code', sa.String(length=20), nullable=False),
    sa.Column('years_of_experience', sa.Integer(), nullable=False),
    sa.Column('has_security_role', sa.Boolean(), nullable=False),
    sa.Column('consented_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('has_security_role = false', name='ck_participants_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anonymous_code')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('repository_path', sa.Text(), nullable=False),
    sa.Column('is_public_dataset', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_path')
    )
    op.create_table('transformations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('original_finding_id', sa.String(length=36), nullable=False),
    sa.Column('transformed_finding_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('anchoring_enabled', sa.Boolean(), nullable=False),
    sa.Column('original_verdict', sa.String(length=20), nullable=True),
    sa.Column('transformed_verdict', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('original_finding_id <> transformed_finding_id', name='ck_transformations_distinct'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('original_finding_id', 'transformed_finding_id', 'anchoring_enabled', name='uq_transformations_pair')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('desarrollador','investigador','lider_tecnico')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('ruleset_version', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('total_findings', sa.Integer(), nullable=False),
    sa.Column('validated_findings', sa.Integer(), nullable=False),
    sa.Column('raw_sarif', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('claimed_by', sa.String(length=120), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('context_purged', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pendiente','en_proceso','completada','fallida')", name='ck_executions_status'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_executions_queue', 'executions', ['status', 'created_at'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('participant_id', sa.String(length=36), nullable=False),
    sa.Column('condition_order', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('first_batch', sa.String(length=10), nullable=False),
    sa.Column('second_batch', sa.String(length=10), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('participant_id', sa.String(length=36), nullable=False),
    sa.Column('value', sa.String(length=20), nullable=False),
    sa.Column('seconds', sa.Float(), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("value IN ('confirmado','descartado','dudoso')", name='ck_decisions_value'),
    sa.CheckConstraint('seconds > 0', name='ck_decisions_seconds'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_decisions_finding', 'decisions', ['finding_id'], unique=False)
    op.create_index('ix_decisions_participant', 'decisions', ['participant_id', 'condition'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('execution_id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=200), nullable=False),
    sa.Column('cwe', sa.String(length=20), nullable=True),
    sa.Column('rule_severity', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('known_truth', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Float(), nullable=True),
    sa.Column('priority_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('end_line >= start_line', name='ck_findings_lines'),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_findings_execution', 'findings', ['execution_id'], unique=False)
    op.create_index('ix_findings_fingerprint', 'findings', ['fingerprint'], unique=False)
    op.create_index('ix_findings_priority', 'findings', ['execution_id', 'priority'], unique=False)
    op.create_table('code_contexts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('enclosing_function', sa.Text(), nullable=False),
    sa.Column('callers', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('sanitizers', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('available_lines', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('source_expression', sa.Text(), nullable=True),
    sa.Column('caller_depth', sa.Integer(), nullable=False),
    sa.Column('degraded_to_file', sa.Boolean(), nullable=False),
    sa.Column('context_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('finding_id')
    )
    op.create_table('verdicts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('model_version', sa.String(length=120), nullable=False),
    sa.Column('prompt_version', sa.String(length=120), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('repetition', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('cited_lines', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('anchor_verified', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('raw_response', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('reused_from', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('attempts BETWEEN 1 AND 2', name='ck_verdicts_attempts'),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name='ck_verdicts_confidence'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('finding_id', 'model', 'model_version', 'repetition', name='uq_verdicts_condition')
    )
    op.create_index('ix_verdicts_finding', 'verdicts', ['finding_id'], unique=False)
    op.create_index('ix_verdicts_model', 'verdicts', ['model', 'model_version', 'repetition'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_verdicts_model', table_name='verdicts')
    op.drop_index('ix_verdicts_finding', table_name='verdicts')
    op.drop_table('verdicts')
    op.drop_table('code_contexts')
    op.drop_index('ix_findings_priority', table_name='findings')
    op.drop_index('ix_findings_fingerprint', table_name='findings')
    op.drop_index('ix_findings_execution', table_name='findings')
    op.drop_table('findings')
    op.drop_index('ix_decisions_participant', table_name='decisions')
    op.drop_index('ix_decisions_finding', table_name='decisions')
    op.drop_table('decisions')
    op.drop_table('sessions')
    op.drop_index('ix_executions_queue', table_name='executions')
    op.drop_table('executions')
    op.drop_table('users')
    op.drop_table('transformations')
    op.drop_table('projects')
    op.drop_table('participants')
    # ### end Alembic commands ###
